training:
  epoch: 2
  train_batch: 8
  val_batch: 4
  version: 2
  loss: binary_crossentropy
  
data:
  gcp:
    test: gs://aj-instance-1/data/data/test
    train: gs:/aj-instance-1/data/data/train
  local:
    test: ./data/test
    train: ./data/train

type: cat_dog_clf

data_generator:
  class_mode: binary

save_model:
  gcp :
    path_prefix: gs://aj-instance-1/data/data/test # dummy  
  local:
    path_prefix: ./models/

  
image:
  size: 224
  raw_data:
    test: aj-instance-1/data/data/test # dummy
    train: aj-instance-1/data/data/test # dummy

platform: gcp
  
