training:
  epoch: 10
  train_batch: 32
  val_batch: 4
  version: 1
  loss: binary_crossentropy
  
data:
  gcp:
    test: gs://kubeflow-test-288607-kubeflowpipelines-default/transfer-learning-keras-training/data/test
    train: gs://kubeflow-test-288607-kubeflowpipelines-default/transfer-learning-keras-training/data/train
  local:
    test: ./data/test
    train: ./data/train

type: cat_dog_clf

data_generator:
  class_mode: binary

save_model:
  gcp :
    path_prefix: gs://kubeflow-test-288607-kubeflowpipelines-default/transfer-learning-keras-training/models/ 
  local:
    path_prefix: ./models/

  
image:
  size: 150 

platform: local
  
