training:
  epoch: 2
  train_batch: 8
  val_batch: 4
  version: 8
  loss: binary_crossentropy
  
data:
  gcp:
    test: gs://kubeflow-test-288607-kubeflowpipelines-default/transfer-learning-keras-training/data/tfrecord
    train: gs://kubeflow-test-288607-kubeflowpipelines-default/transfer-learning-keras-training/data/tfrecord
  local:
    test: ./data/test
    train: ./data/train

type: cat_dog_clf

data_generator:
  class_mode: binary

save_model:
  gcp :
    path_prefix: gs://kubeflow-test-288607-kubeflowpipelines-default/transfer-learning-keras-training/models/ # dummy  
  local:
    path_prefix: ./models/

export_model:
  model_path: 
  model_pb_path:  '/home/dldevmax/projects/gopi/facedetection/models/pb/'
  model_pb_name:  'facenet_model.pb'



  
image:
  size: 224
  show_image: False
  raw_data:
    path: gs://kubeflow-test-288607-kubeflowpipelines-default/transfer-learning-keras-training/data/raw_data
    test: gs://kubeflow-test-288607-kubeflowpipelines-default/transfer-learning-keras-training/data/raw_data/test  #./data/test # dummy
    train: gs://kubeflow-test-288607-kubeflowpipelines-default/transfer-learning-keras-training/data/raw_data/train #./data/train # dummy
    tfrecord_path: gs://kubeflow-test-288607-kubeflowpipelines-default/transfer-learning-keras-training/data/tfrecord
    test_shard: 4
    train_shard: 4
    threads: 4
    label_file: ./labels_file

platform: gcp
  
